package Ch02;

class A{
	public void Ex1() throws NullPointerException 
	{
		System.out.println("A's Ex1 Func Call!");
		String a = null;
//		a.toString();
		}
}

class B{
	public void Ex2() throws AWTException {
		System.out.println("B's Ex2 Func Call!");
		throw new AWTExeption("AWT 예외발생");
	}
}
public class C06ThrowAndThrowsMain예외처리파트중요 {

	public static void main(String[] args) {
		// 한쪽으로 예외를 던질때(몰아줄때) 사용 ★★★★
		
		A ob1 = new A();
		B ob2 = new B();
		try {
		ob1.Ex1();
		ob2.Ex2();
		}catch(NullPointerException e1) {
			System.out.println("NULL 예외처리");
		}catch(AWTExeption e2) {
			System.out.println("AWT 예외처리!");
		}
	}

}
